# .github/workflows/deploy.yml

name: Test, Build, and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  SERVICE: yolo-api-service
  REGION: us-central1

# In .github/workflows/deploy.yml

jobs:
  #-------------------------
  # Job 1: Run Tests 🧪
  #-------------------------
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      # --- ADD THIS NEW STEP ---
      - name: Install pytest
        run: pip install pytest
      # -------------------------

      - name: Run tests with pytest
        run: python -m pytest tests/

  #-------------------------
  # Job 2: Build Image 📦
  #-------------------------
  build:
    name: Build and Push Image
    # This job depends on the 'test' job succeeding
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/api-images/fastapi-yolo:${{ github.sha }} .
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/api-images/fastapi-yolo:${{ github.sha }}

  #-------------------------
  # Job 3: Deploy to Cloud 🚀
  #-------------------------
  deploy:
    name: Deploy to Cloud Run
    # This job depends on the 'build' job succeeding
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/api-images/fastapi-yolo:${{ github.sha }}
          flags: "--memory=2Gi --allow-unauthenticated"
      
      - name: Show Output URL
        run: echo "Successfully deployed to ${{ steps.deploy.outputs.url }}"
